#!/usr/bin/env python
# coding: utf-8
##libaoda
##################################################################
import os
import math
import shutil
import glob
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import argparse

parser = argparse.ArgumentParser(
    description='Candidate second sifting program, the input file is the .bestprof file generated by the prepfold command.',
    usage='use "%(prog)s --help" for more information',
    formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('-ncpu', '--ncpu', type=int, default=1, 
                    help='The cups  were used.\nDefault=1')
parser.add_argument('-zmax', '--zmax', type=int, 
                    help='The zmax  value.')
parser.add_argument('-snr', '--snr', type=float, default=9, 
                    help='The Average profile SNR threshold. Max(I)/Std(I[8:22].\nDefault=10')
parser.add_argument('-median', '--median', type=float, default=10, 
                    help='The Average profile median judgment threshold.Max(I)/median(I[8:20].\nDefault=10')
parser.add_argument('-mean', '--mean', type=float, default=100, 
                    help='The Average profile mean judgment threshold.Max(I)/mean(I[10:20].\nDefault=100')
parser = parser.parse_args()
snr_threshold = parser.snr
median_threshold = parser.median
mean_threshold = parser.mean
zmax = parser.zmax
ncpu = parser.ncpu

x=os.getcwd()
name=os.path.split(os.path.split(x)[0])[1]
file_list =(glob.glob("*.pfd.bestprof"))
date=[]
P=[]
SNR=[]
file=[]
jishu=0
for file_name in file_list :
    match = re.search(r"_(.*?)TH",file_name)
    if match:
        suzi = re.search(r"\d+\.\d*",file_name)
    date.append(file_name[0:4])
    data = np.loadtxt(file_name)
    prof_x = data[:,0]
    prof_y = data[:,1]
    prof_y =  [float('{:.10f}'.format(a)) for a in prof_y]
    prof_y = (((prof_y/np.max(prof_y))) - 0.9999)*10000
    prof_y = prof_y - np.mean(prof_y)
    peak_index = np.argmax(prof_y)
    peak_value = prof_y[peak_index]
    shift = len(prof_y) // 2 - peak_index
    prof_y = np.roll(prof_y, shift)
    prof_y = prof_y-np.min(prof_y)
    prof_y /= np.max(prof_y)
    prof_y=prof_y**2
    prof_y /= np.max(prof_y)
    #print(prof_y)
    snr = round((np.max(prof_y)/np.std(prof_y[8:22])),2)
    median = round((np.max(prof_y)/np.median(prof_y[8:20])),2)
    mean = round((np.max(prof_y)/  (np.mean(prof_y[10:20]**4)) ),2)
    if (snr > snr_threshold or median > median_threshold) and mean > mean_threshold :
        if match :
            #plt.plot(prof_x,prof_y)
            #plt.show()
            #print(file_name[:-9],snr,mean)
            file.append(file_name[:-9])
            value = format(suzi.group(0))
            SNR.append(snr)
            P.append(value)
        else: 
            file.append(file_name[:-9])
            jishu += 1
            SNR.append(snr)
            P.append(jishu)
#####################################################
Dir = ('second_sifting')
if os.path.exists(Dir):
    shutil.rmtree(Dir)
os.makedirs("second_sifting")
###################################################
f = open("second_sifting.sh", "w+")
for i in range (len(file)):
    a=("cp "+str(file[i])+".png "+"second_sifting ") 
    f.write(a)
    f.write("\n")
f.close()
#####################################################
os.system('bash second_sifting.sh')
##################################################
